### ISSUE TITLE
issues with running module / run.py

### ISSUE THREAD

**Issue by Parameter69** [kamushadenes/cefevent#16]
I get this error when running run.py. File /con/CEFtools/logfiles/test_out.log contains a CSV file with CEF header.
It seems the module struggles finding his own imports. Same on Linux or Windows. 

[cefevent]# /opt/rh/rh-python36/root/bin/python ./run.py --host localhost --port 10514 --auto_send --eps 10000 /con/CEFtools/logfiles/test_out.log
Traceback (most recent call last):
  File "./run.py", line 2, in <module>
    from cefevent import CEFSender, CEFEvent
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/cefevent/cefevent.py", line 4, in <module>
    from .extensions import extension_dictionary
ImportError: attempted relative import with no known parent package

Ok, so I remove the . in .extensions to have it find it, we go one step further

[cefevent]# /opt/rh/rh-python36/root/bin/python ./run.py --host localhost --port 10514 --auto_send --eps 10000 /con/CEFtools/logfiles/test_out.log
Traceback (most recent call last):
  File "./run.py", line 2, in <module>
    from cefevent import CEFSender, CEFEvent
ImportError: cannot import name 'CEFSender'

So I modify the import line to 
from cefsender import CEFSender

And I get this:

[cefevent]# /opt/rh/rh-python36/root/bin/python ./run.py --host localhost --port 10514 --auto_send --eps 10000 /con/CEFtools/logfiles/test_out.log
Traceback (most recent call last):
  File "./run.py", line 4, in <module>
    from cefsender import CEFSender
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/cefevent/cefsender.py", line 6, in <module>
    from cefevent.syslog import Syslog
ModuleNotFoundError: No module named 'cefevent.syslog'; 'cefevent' is not a package

All righty, trying with modifying that line in cefsender.py to 
from cefevent import CEFEvent

I don’t think it requires all this tweaking, may be something I’m missing. 

Also, it seems to resend the same events over and over. How can I make it only send the content of the file once?
And there seem to be a few fields missing from extensions.py (deviceVendor, deviceProduct, Name, deviceEventClassId, requestContext etc). It would be good to add them. Please refer to the list sent to you by email.

Thanks

**Comment by kamushadenes** [comment]
Hello.

Please try release https://github.com/kamushadenes/cefevent/releases/tag/0.5.4.

I also added support for sending events only once, and made it the default behavior.

Please let me know if this works.

**Comment by kamushadenes** [comment]
Closing due to inactivity
